name: Publish to PyPI
  # Set the Node 24 flag at the job level to ensure it applies to all steps
env:
   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
